package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"time"

	"github.com/gorilla/mux"
)

type Article struct {
	Id      string `json:"Id"`
	Title   string `json:"Title"`
	Desc    string `json:"desc"`
	Content string `json:"content"`
}

// let's declare a global Articles array
// that we can then populate in our main function
// to simulate a database
var Articles []Article

func homePage(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Welcome to the HomePage!")
	fmt.Println("Endpoint Hit: homePage")
}

func returnAllArticles(w http.ResponseWriter, r *http.Request) {
	fmt.Println("Endpoint Hit: returnAllArticles")
	json.NewEncoder(w).Encode(Articles)
}

func returnSingleArticle(w http.ResponseWriter, r *http.Request) {
	vars := mux.Vars(r)
	key := vars["id"]

	// Loop over all of our Articles
	// if the article.Id equals the key we pass in
	// return the article encoded as JSON
	for _, article := range Articles {
		if article.Id == key {
			json.NewEncoder(w).Encode(article)
		}
	}
}

func createNewArticle(w http.ResponseWriter, r *http.Request) {
	// get the body of our POST request
	// unmarshal this into a new Article struct
	// append this to our Articles array.
	reqBody, _ := ioutil.ReadAll(r.Body)
	var article Article
	json.Unmarshal(reqBody, &article)
	// update our global Articles array to include
	// our new Article
	Articles = append(Articles, article)

	json.NewEncoder(w).Encode(article)
}

func deleteArticle(w http.ResponseWriter, r *http.Request) {
	// once again, we will need to parse the path parameters
	vars := mux.Vars(r)
	// we will need to extract the `id` of the article we
	// wish to delete
	id := vars["id"]

	// we then need to loop through all our articles
	for index, article := range Articles {
		// if our id path parameter matches one of our
		// articles
		if article.Id == id {
			// updates our Articles array to remove the
			// article
			Articles = append(Articles[:index], Articles[index+1:]...)
		}
	}
}

type AutoGenerated struct {
	Status string `json:"status"`
	Data   []struct {
		Job       string `json:"job"`
		NodeName  string `json:"node_name"`
		Pod       string `json:"pod"`
		Container string `json:"container"`
		Filename  string `json:"filename"`
		Namespace string `json:"namespace"`
		Stream    string `json:"stream"`
		App       string `json:"app"`
	} `json:"data"`
}

func getLokiLabels(w http.ResponseWriter, r *http.Request) {

	vars := mux.Vars(r)
	selectedNamespace := vars["namespace"]

	resp, err := http.Get("http://localhost:8081/loki/api/v1/series?match[]={namespace=\"" + selectedNamespace + "\"}")
	if err != nil {
		log.Fatal(err)
	}

	defer resp.Body.Close()

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}

	var summary = new(AutoGenerated)
	err3 := json.Unmarshal(body, &summary)
	if err3 != nil {
		fmt.Println("whoops:", err3)
		//outputs: whoops: <nil>
	}
	// fmt.Println(summary.Data[0])
	var ls []string
	// ls = append(ls, "4")
	fmt.Println("Available selectors in the \"" + selectedNamespace + "\" are:")
	for _, i := range summary.Data {
		ls = append(ls, i.App)
		fmt.Println(i.App)
	}

	processed := map[string]struct{}{}
	runner := 0
	for _, s := range ls {
		if _, exists := processed[s]; !exists {
			// If this value has not been seen yet, add it to the list
			processed[s] = struct{}{}
			ls[runner] = s
			runner++
		}
	}
	ls = ls[:runner]

	json.NewEncoder(w).Encode(ls)
}

func getLokiLogs(w http.ResponseWriter, r *http.Request) {
	// vars := mux.Vars(r)
	/* selectedNamespace := vars["namespace"]
	selectedAppLabel := vars["app"]
	selectedStartTime := vars["start"]
	selectedEndTime := vars["end"] */

	selectedNamespace := r.URL.Query().Get("namespace")
	selectedAppLabel := r.URL.Query().Get("app")
	selectedStartTime := r.URL.Query().Get("start")
	selectedEndTime := r.URL.Query().Get("end")
	if selectedNamespace == "" {
		w.WriteHeader(http.StatusNotFound)
		w.Header().Set("Content-Type", "application/json")
		resp := make(map[string]string)
		resp["message"] = "A namespace must be specified"
		jsonResp, err := json.Marshal(resp)
		if err != nil {
			log.Fatalf("Error happened in JSON marshal. Err: %s", err)
		}
		w.Write(jsonResp)
		fmt.Println(jsonResp)
		return
	}
	if selectedAppLabel == "" {
		w.WriteHeader(http.StatusNotFound)
		w.Header().Set("Content-Type", "application/json")
		resp := make(map[string]string)
		resp["message"] = "An app selector must be specified"
		jsonResp, err := json.Marshal(resp)
		if err != nil {
			log.Fatalf("Error happened in JSON marshal. Err: %s", err)
		}
		w.Write(jsonResp)
		return
	}
	if selectedStartTime == "" {
		// default to 5 minutes ago
		selectedStartTime = string(getCurrentTimestamp() - 300000000000)
	}
	if selectedEndTime == "" {
		// default to now
		selectedStartTime = string(getCurrentTimestamp())
	}

	fmt.Println(selectedAppLabel, selectedNamespace, string(selectedStartTime), string(selectedEndTime))

	json.NewEncoder(w).Encode("Success!")
}

func getCurrentTimestamp() int64 {
	return time.Now().UnixNano()
}

func handleRequests() {
	// creates a new instance of a mux router
	myRouter := mux.NewRouter().StrictSlash(true)
	// replace http.HandleFunc with myRouter.HandleFunc
	myRouter.HandleFunc("/", homePage)
	myRouter.HandleFunc("/articles", returnAllArticles)
	myRouter.HandleFunc("/article", createNewArticle).Methods("POST")
	myRouter.HandleFunc("/article/{id}", deleteArticle).Methods("DELETE")
	myRouter.HandleFunc("/article/{id}", returnSingleArticle)
	myRouter.HandleFunc("/getLokiLabels/{namespace}", getLokiLabels)
	myRouter.HandleFunc("/getLokiLogs", getLokiLogs)
	log.Fatal(http.ListenAndServe(":9003", myRouter))
}

func main() {
	fmt.Println("Rest API v2.0 - Mux Routers" + "\n")
	Articles = []Article{
		Article{Id: "1", Title: "Hello", Desc: "Article Description", Content: "Article Content"},
		Article{Id: "2", Title: "Hello 2", Desc: "Article Description", Content: "Article Content"},
	}
	handleRequests()
}
